### ISSUE TITLE
installation cannot be continued

### ISSUE THREAD

**Issue by Muphet** [Creatiwity/wityCMS#147]
I started with fresh installation to test cms out. i am stuck in installation process because there is no application to choose. Both "home application" and "main admin application" select fields are empty. How to solve this?

**Comment by JohanDufau** [comment]
Hello,

Thanks for your feedback.

It seems like the installator does not have read access to the folder /apps/ on your environment.
Can you tell me on which environment you are testing the installation? (windows/linux/macos + server: apache/nginx?)

Can you send a screenshot also of the interface?

Thank you!

Johan
