### ISSUE TITLE
Loading.. button, doesn't go to Admin panel

### ISSUE THREAD

**Issue by JeroenSteen** [Creatiwity/wityCMS#148]
I'm trying to install WityCMS, with Laragon 3.1 with PHP 7.1.5. During the installer proces I used root, and 3306 as settings. I hit Launch install button, and it says Loading.. for a whill. I can see that the database haves Wity tables. But the Loading page doesn't do anything. When I refresh the url, it goes back to the beginning of the installer proces. Why does this happen?

**Comment by JohanDufau** [comment]
Hello!
Sorry for the late answer...
I just tried the installation process on PHP 7.2.1 with MAMP and I had no issues.
Can you check your PHP error logs and paste the error that occurred?

Thank you!
