### ISSUE TITLE
Get back to work please

### ISSUE THREAD

**Issue by WebCrew** [Creatiwity/wityCMS#149]
Hi Mate,

You have come so far and Your little CMS is awesome, even to create a own template tag language is awesome. You did a great job, so PLEASE dont give up and get back to work.

I know its a bit frustrating if only 13 stars arrived at Your project, but You`ll get more and more peoples interested into Your CMS.

I hope You`ll think about it.

Kind regards, Andy

**Comment by JohanDufau** [comment]
Hello Andy!

Thanks for your feedback. Yeah, we are terribly busy currently at work and it is difficult to find time to push some new features on the CMS. But we are thinking about it :)

Do you use the CMS on one of your websites?
We'd love to see that.

Best,
Johan

**Comment by WebCrew** [comment]
Thx for replying 😀
I use your CMS and at the Moment I  Setup a big new website with it (some
kind of a smaller Art Magazin). Trying to see whats possible with Wity or
when the limits of what is possible are reached. 😂
If I finished the setup i'll show you the result 😊

Kind regards from Stuttgart/Germany,
Andi

Johan Dufau <notifications@github.com> schrieb am Di., 22. Mai 2018, 23:14:

**Comment by JohanDufau** [comment]
Hello!
We just released the v0.6.2 including a few fixes 🍾  :
https://github.com/Creatiwity/wityCMS/releases/tag/0.6.2

Don't hesitate to give feedbacks!
Best,
Johan

**Comment by WebCrew** [comment]
Thanks for the update :)
