### ISSUE TITLE
The page isn’t redirecting properly

### ISSUE THREAD

**Issue by GaneshKandu** [Creatiwity/wityCMS#151]
Hi,

I am Redirection issue while loading front end
**The page isn’t redirecting properly**
when i am changing ```Application par défaut``` setting to ```lang``` and ```user```

- Its not fully translated to English

i am created page ```testpage``` and saved successfully ```La page ganesh a été modifiée avec succès.```
**http://mydomain/subdirectory/2-testpage**
but getting this error message ```Désolé mais wityCMS n'a pas été en mesure de trouver la page demandée.``` on same url

**Comment by JohanDufau** [comment]
Hello,

In Settings > Languages, you should disable French and set English as a default language in your case.

Do you have the file `.htaccess` (contained at the root of the zip file of the release) in your root directory of wityCMS? If not, Apache will not be able to redirect to the root index.php and then to find your page `2-testpage`.

Let me know if this helps.

**Comment by GaneshKandu** [comment]
Hi,

> In Settings > Languages, you should disable French and set English as a default language in your case.

did same but still not working getting same error

![screenshot-webuzo web-2018-06-04-16-49-34](https://user-images.githubusercontent.com/12833130/40914952-b7c1268e-67e9-11e8-85fd-14d442d29a9a.png)

> Do you have the file .htaccess in your root directory of wityCMS?

yes ! i have .htaccess in root of wityCMS

![img_20180604](https://user-images.githubusercontent.com/12833130/40915037-1b36005e-67ea-11e8-9136-3e93bbdafe2b.png)

This is .htaccess of wityCMS

```php
# Use utf8 by default
AddDefaultCharset UTF-8

<IfModule mod_rewrite.c>
	# Activate rewriting
	RewriteEngine on

	# Rule to redirect on www site
	#RewriteCond %{HTTP_HOST} ^site\.com$
	#RewriteRule ^(.*) http://www.site.com/$1 [QSA,L,R=301]

	# Redirect everything but a physical file to wityCMS
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule . index.php [L]
</IfModule>
```

**Comment by GaneshKandu** [comment]
**i think this is cause by**

```apps/lang/front/main.php Line no 39```
```php
		switch ($lang) {
			default:
			case 'fr':
				$_SESSION['current_lang_code'] = 'fr_FR';
				$_SESSION['current_lang_iso'] = 'fr';
				break;

			case 'en':
				$_SESSION['current_lang_code'] = 'en_EN';
				$_SESSION['current_lang_iso'] = 'en';
				break;

			case 'es':
				$_SESSION['current_lang_code'] = 'es_ES';
				$_SESSION['current_lang_iso'] = 'es';
				break;
		}

		// Redirection
		$this->setHeader('Location', WRoute::getReferer()); // Line 39
	}
}
```
AND

```apps/user/front/main.php Line No 38```

```php
	/**
	 * The Login action allows a user to connect to his account.
	 *
	 * @param array $params Redirect is expected in this array
	 * @return array Model containing the redirect link
	 */
	protected function login($params) {
		$redirect = $this->model->getRedirectURLWithParams($params); //line no 38

		if ($this->session->isConnected()) {
			$this->setHeader('Location', $redirect);
			return WNote::error('user_already_connected', 'No need to access to the login form since you are already connected.');
		}
```

i am not sure but works when commenting line 38 of ```user``` and 39 ```lang``` ```main.php``` file

**Comment by JohanDufau** [comment]
Hello Ganesh,
Indeed, you are not supposed to use `lang` and `user` apps as `Default application` because those apps will always try to redirect the user to another page of the website after being executed.
Can you use a different default app, such as the `news` app or `contact` app, or a custom app of yours?

Let me know if this is better.
Thanks!

**Comment by GaneshKandu** [comment]
@JohanDufau 
yes i can use other custom apps and are works fine
except ```lang``` and ```user```

**Comment by JohanDufau** [comment]
Hello,
Yeah, please, do not use lang & user functions. They will be hidden from the list in a future version.

Thx!
