### ISSUE TITLE
The Local File Inclusion vulnerability in /system/WCore/WHelper.php

### ISSUE THREAD

**Issue by LessonXK** [Creatiwity/wityCMS#152]
I found a local file inclusion vulnerability.An attacker might include local PHP files or read non-PHP files with this vulnerability.

Reference:
https://xkklq.coding.me/2018/06/07/wityCMS-LFI/

**Comment by JohanDufau** [comment]
Hello,
Thank you for reporting this back!

Here are two fixes:
On helpers inclusion: https://github.com/Creatiwity/wityCMS/commit/66b46b3076daf351738a155b9a39f21bee146d79
On roxy: https://github.com/Creatiwity/wityCMS/commit/4bb5b269af3f5f15552ef488a25408612f893202

What do you think?

**Comment by LessonXK** [comment]
I confirm that the vulnerability has been fixed

**Comment by JohanDufau** [comment]
Great! I will release v0.6.3 with this fix this week.
Thanks again!
