### ISSUE TITLE
WForm

### ISSUE THREAD

**Issue by julien1619** [Creatiwity/wityCMS#36]
WForm est la passerelle qui est chargée d'une part, de mettre en forme les formulaires lors de leur génération coté serveur et de fournir un set de vérifications dynamiques à la saisie coté client, en cohérence avec ce que le développeur a pu demander.
D'autre part c'est la passerelle qui va dispatcher les inputs reçus entre les différentes applications concernées.

Relatif au Rendering multi-app (#8)

**Comment by JohanDufau** [comment]
Won't do: not necessary for now.
