### ISSUE TITLE
Media app

### ISSUE THREAD

**Issue by julien1619** [Creatiwity/wityCMS#68]
Il faudrait un module WMedia (ou une application, ou un mix des 2) qui gérerait tous les médias du site, les uploadés et ceux déjà présents. Il faudrait gérer plusieurs types de contenu : 
* Les images. Pour celles-ci il faudrait une gestion automatique du mode Retina ou de la taille d'écran pour envoyer l'image la plus optimisée possible.
* Les vidéos. Gestion de différents encodages si nécessaire pour différentes qualités de vidéos avec une capacité de streaming.
* Tout le reste.

Il faut donc réfléchir aux utilisations possibles afin de définir l'architecture et l'API idéale. Il faut dans tous les cas une priorité sur les images, pour le reste une simple appli ou helper d'upload combiné à une appli devrait suffire.

**Comment by JohanDufau** [comment]
To be treated in a new ticket if still needed.
