### ISSUE TITLE
Block: Allowing to split theme into multiple semantic files/parts

### ISSUE THREAD

**Issue by julien1619** [Creatiwity/wityCMS#71]
Pour le moment un thème est constitué d'un seul fichier index.html contenant l'intégralité du thème. Celui-ci n'est pas modulable, aux variables php près permettant de tester un état ou un autre.

Or parfois, sur un site, certaines pages nécessitent une présentation globale différente (nombre de colonnes, éléments mis en valeur, ...) et cette feature n'est pas supportée pour le moment.

Il faudrait donc pouvoir morceler un thème en différents blocs pour qu'on puisse assembler ou utiliser ces blocs en fonction de la page consultée.

Par exemple le fichier index.html contiendrait le header et le footer, on pourrait avoir un fichier contenant un agencement en plusieurs colonnes pour le contenu central (colonne menu, colonne contenu, ...). Certaines pages pourraient donc afficher les applications directement dans l'espace central du thème et d'autres dans la colonne contenu.

Ça peut même laisser imaginer qu'une application puisse déporter un morceau de sa view dans des zones prédéfinies du thème.

Par exemple on pourrait vouloir afficher du contenu relatif à une news dans une colonne de droite, celle-ci contenant d'autres éléments/applications par défaut. La view de l'application news donnerait donc un emplacement par défaut à ce bloc dans la view principale de l'application news et sinon, dans le cas où le bloc demandé existe dans le thème, cette boîte irait automatiquement se placer à l'intérieur.

En gros les blocs du thème pourraient définir un placement non pas sous forme de gauche, droite, colonne 1 ou 2, mais plutôt sous forme sémantique : filter, related content, social, secondary menu, ...

**Comment by JohanDufau** [comment]
Les blocks seront implémentés dans la 1.0 et repensés ultérieurement de façon simple.
