### ISSUE TITLE
News v2

### ISSUE THREAD

**Issue by julien1619** [Creatiwity/wityCMS#73]
Dans l'idéal, la nouvelle application News devra permettre les fonctionnalités suivantes : 

## Contenu d'une news

* Images d'en-tête
* Fichiers liés à télécharger (gestionnaire de fichiers avec view déportées grâce à WRetriever ?)
* Associer n'importe quel contenu (un ou plusieurs événements d'un calendrier par exemple) qui pourra s'afficher en gravitation autour de la zone ou dans la zone de news.
* La possibilité de placer les images dans la news (des placements de base avec les nouveaux attributs CSS3 permettraient d'implémenter ça rapidement avec une bonne dégradation)

## Meta

* Système de publication différé, soit par validation (selon permission), soit par date de publication (et d'archivage ?). Et donc possibilité de proposer des news.
* Possibilité d'envoyer un mail à l'éditeur en vu de publier le contenu, avec réponse rapide intégrée au mail (accepter, refuser, refuser sans explication, demande de modification) qui redirige vers la page de l'action, voire qui exécute l'action directement ("publication" et "refuser sans explication" par exemple, alors que pour les autres il faut expliquer).
* Revoir complètement les identifiants de news. Pourquoi est-ce qu'on ne contraindrait rien dans l'adresse de la news (ni id, ni "news") avec par défaut le titre formaté et la seule obligation que ce soit unique ? (cf nesblog.com qui profite de l'adresse pour passer des blagues en rapport avec le contenu avec des adresses du style nesblog.com/news/les-3-mots-cles-de-la-news) On a plus qu'à tester en Ajax l'unicité du lien choisi.

## Views

* Afficher les news non publiées pour l'admin sur le front (avec possibilité de désactiver la visibilité admin) et en ajoutant une classe CSS permettant une stylisation facile (en mettant une police plus claire par exemple, ou une outline).
* Carousel de news (avec config sur le nombre de news à afficher, la catégorie, bref le filtrage).
* Une view détaillée de la news intégrant les éléments relatifs, et pourquoi pas intégrer les éléments relatifs dans les listes de news mais en petits, sous forme de tags cliquables qui renverraient sur les pages détaillées de ces éléments ?

- flux RSS

**Comment by JohanDufau** [comment]
Fixé par commit 777ff5aff6aa42760d30f9783ba7715769a904f1
