### ISSUE TITLE
Language Management Improvement

### ISSUE THREAD

**Issue by cairwy** [Creatiwity/wityCMS#85]
As I'm working on the Lang Editor app, I suggest a few improvement on the WLang object. I started experimentation on my own fork ;)

Instead of a purely static object, I suggest that the languages management stays static  (array of languages, etc...) but that the languages themselves are stored in individual objects. So we would have as static variable at least:
- Languages to use in order of priority
- List of language directories registered
- Current Language

WLang object itself (I think we should rename it and keep WLang as the static thing) would just contains:
- Language values associated to their constant

This way, we can use WLang to load language files separately from the core itself and proceed to modification of language files..

Also, as I went through the code, I noticed that in case one key doesn't exist in the current files, it will load each language files until the key is found !! And then load back the default language ! That doesn't seem very effective ^^
Instead, I suggest this: at init of the static objects, we read all the keys in the DEFAULT APP LANGUAGE (which should contains all of them...) and assign this values to the $values. Then, we load the preferred one. If the key doesn't exist, we try with the second preferred one, etc, etc... This would work but in case a lot of language exists, it might a performance killer :(
Also, there would be different constructors in the object WLang, one of used by the core to load the current language which would used the above logic and another one which would just construct a language according to an app name + a language ;)

I will implement these ideas if you are okay with them !!

**Comment by JohanDufau** [comment]
Won't do: not mandatory for now. An update of WLang will be designed in the next main update.
