### ISSUE TITLE
Config variables for each application

### ISSUE THREAD

**Issue by cairwy** [Creatiwity/wityCMS#90]
As I have been writing a few applications in the past weeks, I noticed a recurring need throughout application writing : a quick'n'easy way to add config variables for some application. I had a look on the WConfig system, but it seems to be an overkill to have a file for each application... As it would require to write an interface for each application to edit those values without going into the sources (with can be very useful in general).

I suggest to create an application or a WXxxx to fulfill this need. The requirements for this would be to be able to:
- Store variables into a SQL table
- Provide an interface in the administration panel to edit the variables
- Be able to specify the types of each variables, containing at least:
 * Text (=VARCHAR)
 * Textarea (=TEXT)
 * Date
 * Int/Float
 * Enum
- Provide the relevant editor for each type
- For perfo issue, the system should have a cache and not load the entire thing at construct...
- Easy access to those variables in the code

This app will also be the config app to edit WityCMS config itself :)

I see no problem for all of those specifications, except the last one as it would require to call the "getModel" method, which is not nice ! For "beauty of the code" (no special need for this app), I think it might require a huge effort of integration ! We could create some 'native apps' with special treatment... It is debatable !
An elegant solution (which would also make sens) would be to include the access to the DB in WConfig and use it if we called get() with a special path such as 'vars.' or 'app_config.' or simply a different method.

I think i will write an app anyway and we can discuss the WConfig integration later...

**Comment by JohanDufau** [comment]
Won't do: for now, each application handle its configuration (if any) by itself.
