### ISSUE TITLE
Remote language variable access

### ISSUE THREAD

**Issue by cairwy** [Creatiwity/wityCMS#91]
As I'm writing the config app, I'm facing an issue once again: error display with language management for ajax response !
For now, most of it is done in the server code through the response (with WNote and WLang::get). In Javascript, we cannot access WLang directly and that causes several issue for me.
For instance, now, if their is no answer or bad response from the server (like page not found or whatever) and if I want to display an error accordingly, I can't do any language management whatsoever !
My idea is to add a special access (like /m/, /v/, etc...), by app, that would allow request for lang variables.
I think it is doable quickly, but I wonder what kind of performance we could except...
What do you think ?
Maybe we can just write a JS library that does the job... maybe more efficient :-)

**Comment by JohanDufau** [comment]
Won't do: for now, it is not mandatory. Moreover, and update of WLang will be issued in next release.
