### ISSUE TITLE
Form Compiler

### ISSUE THREAD

**Issue by cairwy** [Creatiwity/wityCMS#92]
I just finished to code a first version of a "form compiler".
It allows to describe a html form with PHP in a array such as :
```php
Array ('action' => url,
         'change' => url,
         'method' => POST || GET,
         'submit_text' => name,
         'nodes' => 
             array(name_of_input =>
                    array('label' => name, 
                            'type' => text, 
                            'value' => value), 
             ...)
)
```

Then, you just put {WForm name_of_form} in the template, and here it goes ! For now, it is bootstrap form-horizontal, but I have an idea fora more customizable solution, using templates. 

For now, it handles text and password field for now, but as the core is ready, it's easy to add whatever we like :) I will probably do select and checkboxes/radio quickly. I'm using the template compiler for the nodes, so we can use a specific render if we want to ! (I will add the option into the php array for each node)

It handles javascript validation of the fields (if the specific js file is assigned, obviously), using ajax and the url given in the 'change' parameter. You can use a custom javascript function as well. The JS has been built as jquery plugin so it possible to adapt it for each form and node (there are default options, global options for the entire form and options for a specific node...).

I need to add customization of change url per nodes on the PHP side (quite simple with array_replace_recursive magic) and maybe some other features (Reset ? Nicer error display, etc...).

I'm thinking about wrapping that into a Helper and a separate library for the js (so that you can use it or not). Or if the code is nice enough and the features interesting enough, we can add it directly into the Compiler !
I can give you my code if you want to have a look! I will try to clear it as much as possible ^^
I also have a editable table libraries, which can be very useful for all sorts of things... I showed it to Johan, tell me if you want the code ! The JS is not as clear as for the form though ^^

**Comment by JohanDufau** [comment]
For now, we use custom forms in every app.
A general form compiler can be investigated but is not the top priority for now. Moreover, I believe we can find existing and efficient form compilers in the litterature.
